name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20  # Specify your desired Go version

#       - name: Set up MongoDB
#         uses: mongodb/setup-mongodb@v1
#         with:
#           mongodb-version: '4.4'  # Specify your desired MongoDB version

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build and Test
        run: |
          go run main.go
#          go build ./...
#          go test -v ./...
